#:tombi schema.strict = false
[window]
padding = { x = 12, y = 12 }
decorations = "none"
opacity = 0.75
[font]
normal = { family = "CaskaydiaCove NFM" }
[terminal]
shell = { program = "pwsh.exe", args = [ "-NoLogo" ] }
[mouse]
hide_when_typing = false
[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "ToggleViMode" },
  { key = "I", mode = "Vi", action = "Up" },
  { key = "J", mode = "Vi", action = "Left" },
  { key = "K", mode = "Vi", action = "Down" },
  { key = "L", mode = "Vi", action = "Right" },
  { key = "H", mode = "Vi", action = "None" },
  { key = "U", mode = "Vi", action = "WordLeft" },
  { key = "O", mode = "Vi", action = "WordRightEnd" },
  { key = "V", mode = "Vi", action = "ToggleNormalSelection" },
  { key = "M", mode = "Vi", action = "Bracket" },
  { key = "J", mods = "Alt", mode = "Vi", action = "First" },
  { key = "L", mods = "Alt", mode = "Vi", action = "Last" },
  { key = "K", mods = "Alt", mode = "Vi", action = "ScrollHalfPageDown" },
  { key = "I", mods = "Alt", mode = "Vi", action = "ScrollHalfPageUp" },
  { key = "L", mods = "Shift", mode = "Vi", action = "None" },
  { key = "C", mods = "Control | Shift", mode = "Vi", action = "Copy" },
  { key = "Escape", mode = "Vi", action = "ToggleViMode"}
]
# nord theme thanks to https://gist.github.com/candidtim/6097565040a3aec839a8a2d28cb8887d
[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"
[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"
[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"
[colors.selection]
text = "CellForeground"
background = "#4c566a"
[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"
[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"
[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"
[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"
