include colors.conf

background_opacity 0.75
window_padding_width 4

enable_audio_bell no

font_family "CaskaydiaCove Nerd Font Mono"
cursor_trail 100
cursor_trail_start_threshold 2
tab_bar_min_tabs 2
tab_fade 1

shell /usr/bin/pwsh
editor /home/nspc911/.cargo/bin/hx
