repo = "helix-editor/helix"

remote-branch = "master"

local-branch = "patchy"

pull-requests = [
  "12944", # ":left" ":center" and ":right"
  "13666", # status element styling
  "13197", # welcome screen
  "12806", # path in file picker
  "12369", # icons (disabled for testing)
  # "13448", # harpoon2 for helix (need to look into what it does...)
  # "8362", # scroll bufferline (merge conflict)
  "13206", # word completion
  # "13530", # rainbow brackets (merge conflict)
  "7783", # horizontal picker preview
  "11497", # rounded corners
  # "13627", # better file sizes (merged)
  # "12520", # Picker titles (merge conflict)
  # "12902", # file explorer is a file explorer (merge conflict)
  # "13306", # add custom icon for color swatches (merge conflict)
  "13318", # allow themeing the diagnostics
  # "12151", # allow themeing the items in completion (merge conflict)
]

patches = []
