watch_stylesheet: true
watch_config: true
debug: true
komorebi:
  start_command: "komorebic start --whkd --masir"
  stop_command: "komorebic stop --whkd --masir"
  reload_command: "komorebic stop --whkd --masir && komorebic start --whkd --masir"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: false
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "small"
      border_color: "System"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: false
    dimensions:
      width: "100%"
      height: 31
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["power_menu", "launchpad", "media", "active_window"]
      center: ["clock", "cpu"]
      right:
        [
          "komorebi_active_layout",
          "komorebi_workspaces",
          "bluetooth",
          "wifi",
          "brightness",
          "battery",
          "volume",
          "notifications",
        ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: " {title} "
      label_alt: " {title} - {artist} "
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_right: "toggle_label"
        on_middle: "do_nothing"
      max_field_size:
        label: 40
        label_alt: 40
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: false
      thumbnail_alpha: 255
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 5
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 80
        max_artist_size: 20
        show_source: false
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: " "
      label_icon: true
      label_icon_size: 14
      max_length: 40
      max_length_ellipsis: "-"
      monitor_exclusive: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b %H:%M:%S}"
      label_alt: "{%A %d %B %Y, %H:%M:%S}"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        alignment: "center"
        direction: "down"
        offset_top: 0
        offset_left: 30
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "next_timezone"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: true
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {device_name}"
      icons:
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\u23fb"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 0
      button_row: 5
      buttons:
        shutdown: ["\u23fb", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        signout: ["\udb80\udf43", "Sign out"]
        cancel: ["", "Cancel"]
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:batterysaver-usagedetails"
        on_middle: "do_nothing"
        on_left: "toggle_label"
      charging_options:
        icon_format: "{charging_icon}"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "<span>{wifi_icon}</span>{wifi_name}"
      update_interval: 5000
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_left: "toggle_label"
      ethernet_icon: "\ueba9"
      wifi_icons:
        [
          "\udb82\udd2e",
          "\udb82\udd1f",
          "\udb82\udd22",
          "\udb82\udd25",
          "\udb82\udd28",
        ]
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}%"
      tooltip: false
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons:
        ["\udb80\udcde", "\udb80\udcdd", "\udb80\udcdf", "\udb80\udce0"]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_brightness_menu"
        on_middle: "toggle_level_next"
        on_right: "exec cmd.exe /c start ms-settings:display"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 31
      min_bar_height: 0
      gradient: 0
      reverse: 1
      foreground: "#88C0D0"
      bars_number: 20
      gradient_color_1: "#88C0D0"
      gradient_color_2: "#81A1C1"
      gradient_color_3: "#5E81AC"
      bar_spacing: 0
      bar_width: 2
      sleep_timer: 2
      hide_empty: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon} {layout_name}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "grid",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: "toggle_layout_menu"
        on_middle: "next_layout"
        on_right: "prev_layout"
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 0
        offset_left: 0
        show_layout_icons: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: ""
      label_workspace_btn: "\uf0c8"
      label_workspace_active_btn: "\uf0c8"
      label_workspace_populated_btn: "\uf0c8"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: false
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "do_nothing"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  launchpad:
    type: "yasb.launchpad.LaunchpadWidget"
    options:
      label: "<span>\udb85\udcde</span>"
      search_placeholder: "Search apps..."
      app_icon_size: 48
      window:
        fullscreen: false
        width: 800
        height: 600
        overlay_block: true
      window_style:
        enable_blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
      window_animation:
        fade_in_duration: 0
        fade_out_duration: 0
      callbacks:
        on_left: "toggle_launchpad"
      app_title_shadow:
        enabled: false
        color: "#00000090"
        offset: [1, 1]
        radius: 2
      app_icon_shadow:
        enabled: false
        color: "#00000090"
        offset: [0, 2]
        radius: 8
