hide-cursor-when-typing = false
padding-x = 10
padding-y = [5, -5]
# env-vars = []
confirm-before-quit = false
working-dir = "C:/Users/notso"

# [title]
# placeholder = ""

[editor]
program = "hx"
args = []

[window]
# width = 600
# height = 400
mode = "windowed"
opacity = 0.75
# opacity = 1
blur = false
decorations = "Disabled"

[renderer]
performance = "low"
backend = "automatic"
disable-unfocused-render = true
level = 1
filters = []

[keyboard]
use-kitty-keyboard-protocol = true
[fonts]
family = "CaskaydiaCove NF"
features = ["cv12", "cv18", "calt"]
use-drawable-characters = true
[fonts.regular]
family = "CaskaydiaCove NF"
weight = 400
[fonts.bold]
family = "CaskaydiaCove NF"
weight = 800
[fonts.italic]
family = "CaskaydiaCove NF"
style = "Italic"
weight = 400
[fonts.bold-italic]
family = "CaskaydiaCove NF"
weight = 800

[scroll]
multiplier = 3.0
divider = 1.0

[navigation]
mode = "bookmark"
clickable = false
hide-if-single = false
use-current-path = false
unfocused-split-opacity = 0.99
color-automation = [
  { program = "hx.exe", color = "#FF0000" }
]
open-config-with-split = true

[shell]
program = "pwsh"
args = ["-NoProfileLoadTime", "-NoLogo"]

[bindings]
keys = [
  { key = "{", with = "control", action = "ReceiveChar" },
  { key = "}", with = "control", action = "ReceiveChar" },
  { key = "[", with = "control | shift", action = "ReceiveChar" },
  { key = "]", with = "control | shift", action = "ReceiveChar" },
  { key = "r", with = "control | shift", action = "ReceiveChar" },
  { key = "d", with = "control | shift", action = "ReceiveChar" },
  { key = "t", with = "control | shift", action = "ReceiveChar" },
  { key = "n", with = "control", action = "CreateWindow" },
  { key = "w", with = "control | shift", action = "ReceiveChar" },
  { key = "space", with = "control | shift", action = "ReceiveChar" },
  { key = "[", with = "control", action = "SelectPrevSplit" },
  { key = "]", with = "control", action = "SelectNextSplit" },
  { key = "v", with = "alt", action =  "ToggleViMode" },
  { key = "t", with = "control", action = "CreateTab" },
  { key = "w", with = "control", action = "CloseSplitOrTab" },
  { key = "o", with = "control", action = "OpenConfigEditor" },
  { key = "l", with = "control | shift", action = "SplitRight" },
  { key = "k", with = "control | shift", action = "SplitDown"},
]

[colors]
background = '#2e3441'
foreground = '#d8dee9'
selection-background = '#eceff4'
selection-foreground = '#4c566a'
cursor = '#eceff4'
black = '#3b4252'
red = '#bf616a'
green = '#a3be8c'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b48ead'
cyan = '#88c0d0'
white = '#e5e9f0'
light_black = '#4c566a'
light_red = '#bf616a'
light_green = '#a3be8c'
light_yellow = '#ebcb8b'
light_blue = '#81a1c1'
light_magenta = '#b48ead'
light_cyan = '#8fbcbb'
light_white = '#eceff4'
tabs = "#81a1c1"
tabs-foregroud = "#d8dee9"
tabs-active = "#434c5e"
tabs-active-highlight = "#8fbcbb"
tabs-active-foreground = "#D8DEE9"
bar = "#00000000"
