# From https://github.com/5-pebbles/nordic-helix

"attribute" = "yellow_base"
"comment" = { fg = "gray8", modifiers = ["italic"] } # gray4 is unreadable

"constant" = "magenta_bright"
"constant.builtin" = "magenta_base"
"constant.builtin.boolean" = "magenta_base"
"constant.builtin.character" = "magenta_base"
"constant.builtin.macro" = "magenta_base"
"constant.builtin.numeric" = "magenta_base"
"constant.character" = "green_base"
"constant.character.escape" = "magenta_bright"
"constructor" = "cyan_bright"

"diagnostic.deprecated" = { modifiers = ["dim"] }
"diagnostic.error" = { underline = { color = "red_base", style = "curl" } }
"error" = "red_bright"
"diagnostic.hint" = { underline = { color = "green_base", style = "curl" } }
"hint" = "green_base"
"diagnostic.info" = { underline = { color = "blue1", style = "curl" } }
"info" = "blue1"
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "yellow_base", style = "curl" } }
"warning" = "yellow_base"

"diff.delta" = "blue0"
"diff.minus" = "red_base"
"diff.plus" = "green_base"

"function" = "blue2"
"function.builtin" = "blue1"
"function.method" = "blue2"
"function.macro" = "red_base"
"function.special" = "blue1"

"git.delta.moved" = { bg = "blue2" }

"keyword" = "orange_base"
"keyword.control.conditional" = { fg = "orange_bright", modifiers = ["bold"] }
"keyword.control.exception" = "red_dim"
"keyword.control.import" = { fg = "green_base", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "orange_base", modifiers = ["bold"] }
"keyword.control.return" = "gray6"
"keyword.function" = "orange_dim"
"keyword.operator" = "yellow_dim"

"label" = { fg = "orange_base", modifiers = ["bold"] }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading.1" = { fg = "yellow_bright", modifiers = ["bold", "underlined"] }
"markup.heading.2" = { fg = "orange_bright", modifiers = ["bold"] }
"markup.heading.3" = { fg = "magenta_bright", modifiers = ["bold"] }
"markup.heading.4" = "green_bright"
"markup.heading.5" = { fg = "blue2", modifiers = ["italic"] }
"markup.heading.6" = { fg = "cyan_bright", modifiers = ["italic"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.label" = { fg = "blue2", modifiers = ["underlined"] }
"markup.link.text" = "magenta_dim"
"markup.link.url" = { fg = "blue1", modifiers = ["underlined"] }
"markup.list" = "orange_base"
"markup.list.checked" = "green_base"
"markup.list.unchecked" = "red_base"
"markup.quote" = { fg = "gray4", modifiers = ["italic"] }
"markup.raw" = { bg = "black0", fg = "white2" }
"markup.raw.block" = { bg = "black0", fg = "white2" }
"markup.raw.inline" = { bg = "black0", fg = "white2" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"namespace" = "yellow_dim"
"operator" = "white0"

"punctuation.bracket" = "cyan_bright"
"punctuation.delimiter" = { fg = "gray5", modifiers = ["italic"] }
"punctuation.special" = "orange_base"

"special" = "orange_base"
"string" = "green_base"
"string.regex" = "magenta_bright"

"tag" = "blue1"
"type" = "yellow_bright"

"ui.background" = {}
"ui.bufferline" = {}
# "ui.bufferline.inactive" = { modifiers = ["reversed"], fg = "gray6", bg = "white1" }
"ui.bufferline.active" = { modifiers = ["reversed"] }
"ui.cursor" = { fg = "black0", bg = "white0" }
"ui.cursor.match" = { bg = "gray4" }
"ui.cursor.primary" = { fg = "black1", bg = "white0" }
"ui.cursorline.primary" = { bg = "gray0" }
"ui.gutter.selected" = { bg = "black0" }
"ui.help" = {}
"ui.linenr" = "gray6"
"ui.linenr.selected" = "white3"
"ui.menu" = {}
"ui.menu.scroll" = { fg = "white1", bg = "gray0" }
"ui.menu.selected" = { modifiers = ["underlined"] }
"ui.popup" = {}
"ui.popup.info" = {}
"ui.selection" = { bg = "gray4" }
"ui.text.focus" = { bg = "gray2" }

# virtual stuff
"ui.virtual.indent-guide" = "gray5"
"ui.virtual.inlay-hint" = { fg = "gray8", modifiers = ["dim"] }
"ui.virtual.jump-label" = { fg = "cyan_base", modifiers = ["reversed"] }
"ui.virtual.ruler" = { bg = "gray1" }
"ui.virtual.whitespace" = {}
"ui.virtual.wrap" = "gray4"
"ui.window" = {}
"variable" = "white0"
"variable.builtin" = "blue0"
"variable.other.member" = "cyan_bright"
"variable.parameter" = "whiteblue0"
# statusline
"ui.statusline" = { bg = "black2" }
"ui.statusline.inactive" = { bg = "black0" }
"ui.statusline.normal" = { fg = "blue2", modifiers = ["reversed"] }
"ui.statusline.insert" = { fg = "cyan_bright", modifiers = ["reversed"] }
"ui.statusline.select" = { fg = "yellow_bright", modifiers = ["reversed"] }
# Requires PR:13666
## left
"ui.statusline.version-control" = { bg = "green_bright", fg = "black1" }
"ui.statusline.file-type" = "white2"
"ui.statusline.file-name" = "white2"
"ui.statusline.file-modification-indicator" = { fg = "red_bright", modifiers = ["bold"] }
"ui.statusline.file-encoding" = "black0"
"ui.statusline.register" = "magenta_bright"
## right
"ui.statusline.diagnostics" = "red_bright"
"ui.statusline.workspace-diagnostics" = "orange_bright"
"ui.statusline.position" = "yellow_bright"
"ui.statusline.primary-selection-length" = "green_bright"
"ui.statusline.selections" = "blue2"
"ui.statusline.total-line-numbers" = "magenta_bright"
## inactive left
"ui.statusline.inactive.version-control" = "green_dim"
"ui.statusline.inactive.file-name" = "white0"
"ui.statusline.inactive.file-type" = "white0"
"ui.statusline.inactive.file-modification-indicator" = { fg = "red_dim", modifiers = ["bold"] }
"ui.statusline.inactive.file-encoding" = { bg = "white0", fg = "black0" }
## inactive right
"ui.statusline.inactive.register" = "magenta_bright"
"ui.statusline.inactive.diagnostics" = "red_dim"
"ui.statusline.inactive.workspace-diagnostics" = "orange_dim"
"ui.statusline.inactive.position" = "yellow_dim"
"ui.statusline.inactive.primary-selection-length" = "green_dim"
"ui.statusline.inactive.selections" = "blue0"
"ui.statusline.inactive.total-line-numbers" = "magenta_dim"
rainbow = ["red_base", "orange_base", "yellow_base", "green_base", "cyan_base", "blue1", "magenta_base"]

# Color Palette
[palette]
# Black
black0 = "#191D24"
black1 = "#1E222A"
black2 = "#222630"
# Gray
gray0 = "#242933"
# Polar night
gray1 = "#2E3440"
gray2 = "#3B4252"
gray3 = "#434C5E"
gray4 = "#4C566A"
# a light blue/gray
# from @nightfox.nvim
gray5 = "#60728A"
# extra grays
gray6 = "#727F9A"
gray7 = "#848DAA"
gray8 = "#969BBA"
# White
# reduce_blue variant
white0 = "#C0C8D8"
# Snow storm
white1 = "#D8DEE9"
white2 = "#E5E9F0"
white3 = "#ECEFF4"
whiteblue0 = "#C1D0D1"
# Blue
# Frost
blue0 = "#5E81AC"
blue1 = "#81A1C1"
blue2 = "#88C0D0"
# Cyan:
cyan_base = "#8FBCBB"
cyan_bright = "#9FC6C5"
cyan_dim = "#80B3B2"
# Aurora (from Nord theme)
# Red
red_base = "#BF616A"
red_bright = "#E5727A"
red_dim = "#A04049"
# Orange
orange_base = "#D08770"
orange_bright = "#D79784"
orange_dim = "#AB573D"
# Yellow
yellow_base = "#EBCB8B"
yellow_bright = "#EFD49F"
yellow_dim = "#E7C173"
# Green
green_base = "#A3BE8C"
green_bright = "#B1C89D"
green_dim = "#97B67C"
# Magenta
magenta_base = "#B48EAD"
magenta_bright = "#BE9DB8"
magenta_dim = "#A97EA1"
